import {
  User,
  UserCircle,
  CircleUser,
  UserRound,
  CircleUserRound,
  Bot,
  Ghost,
  Smile,
  Heart,
  Star,
  Sparkles,
  Zap,
  Sun,
  Moon,
  Shield,
  Crown,
  Trophy,
  Award,
  Coffee,
  Flower2,
  Leaf,
  Snowflake,
  Cloud,
  Palette,
  Gem,
  Music,
  Headphones,
  Gamepad2,
  Camera,
  BookOpen,
  Pen,
  Briefcase,
  type LucideIcon,
} from 'lucide-react'

export const AVATAR_ICONS: { id: string; name: string; Icon: LucideIcon }[] = [
  { id: 'user', name: 'User', Icon: User },
  { id: 'user-round', name: 'User Round', Icon: UserRound },
  { id: 'user-circle', name: 'User Circle', Icon: UserCircle },
  { id: 'circle-user', name: 'Circle User', Icon: CircleUser },
  { id: 'circle-user-round', name: 'Circle User Round', Icon: CircleUserRound },
  { id: 'bot', name: 'Bot', Icon: Bot },
  { id: 'ghost', name: 'Ghost', Icon: Ghost },
  { id: 'smile', name: 'Smile', Icon: Smile },
  { id: 'heart', name: 'Heart', Icon: Heart },
  { id: 'star', name: 'Star', Icon: Star },
  { id: 'sparkles', name: 'Sparkles', Icon: Sparkles },
  { id: 'zap', name: 'Zap', Icon: Zap },
  { id: 'sun', name: 'Sun', Icon: Sun },
  { id: 'moon', name: 'Moon', Icon: Moon },
  { id: 'shield', name: 'Shield', Icon: Shield },
  { id: 'crown', name: 'Crown', Icon: Crown },
  { id: 'trophy', name: 'Trophy', Icon: Trophy },
  { id: 'award', name: 'Award', Icon: Award },
  { id: 'coffee', name: 'Coffee', Icon: Coffee },
  { id: 'flower2', name: 'Flower', Icon: Flower2 },
  { id: 'leaf', name: 'Leaf', Icon: Leaf },
  { id: 'snowflake', name: 'Snowflake', Icon: Snowflake },
  { id: 'cloud', name: 'Cloud', Icon: Cloud },
  { id: 'palette', name: 'Palette', Icon: Palette },
  { id: 'gem', name: 'Gem', Icon: Gem },
  { id: 'music', name: 'Music', Icon: Music },
  { id: 'headphones', name: 'Headphones', Icon: Headphones },
  { id: 'gamepad2', name: 'Gamepad', Icon: Gamepad2 },
  { id: 'camera', name: 'Camera', Icon: Camera },
  { id: 'book-open', name: 'Book', Icon: BookOpen },
  { id: 'pen', name: 'Pen', Icon: Pen },
  { id: 'briefcase', name: 'Briefcase', Icon: Briefcase },
]

export function getAvatarIcon(id: string) {
  return AVATAR_ICONS.find((a) => a.id === id) ?? AVATAR_ICONS[0]
}
